### PR TITLE
Implement import for resource_security_rule_group

### PR DESCRIPTION
**Pull request by gliptak**
@shinmog please review

### CODE REVIEW

**Comment by gliptak** [comment]
@radeksimko @shinmog please review

**Comment by shinmog** [comment]
@gliptak 

The resource ID is not the vsys, but rather a base64 encoding of a few different facts about the rule grouping.  As such, it will be very prone to error, which is why no `_group` resource supports importing.  This was intentional.

Just FYI, @radeksimko is not a provider maintainer, he works for HashiCorp.

**Comment by gliptak** [comment]
@shinmog thank you for the explanation. is there a way to query/generate the rule grouping name?

**Comment by shinmog** [comment]
You can see the logic to create the firewall terraform ID [here](https://github.com/terraform-providers/terraform-provider-panos/blob/master/panos/resource_security_rule_group.go#L281) (if this was not what you were asking let me know).

**Pull request closed without merging**
